from database import conn


cursor = conn.cursor()

create_table_sql = """
CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    PRIMARY KEY (employee_id)
)
"""
cursor.execute(create_table_sql)
print("테이블 생성")